// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8d4SSK73KEyRaA1d2M3YYQsKrOg4yTA',
    appId: '1:578568155957:web:28ce635d902f090646127c',
    messagingSenderId: '578568155957',
    projectId: 'project-flutter-api',
    authDomain: 'project-flutter-api.firebaseapp.com',
    storageBucket: 'project-flutter-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3xbqt880XpvvUVp4XdSYZAOZckiDkmI',
    appId: '1:578568155957:android:42880f33af4c62f646127c',
    messagingSenderId: '578568155957',
    projectId: 'project-flutter-api',
    storageBucket: 'project-flutter-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJhDHWBZGumTAXT7n7hNsmf8gScNGeTUE',
    appId: '1:578568155957:ios:c5972838b1eb892046127c',
    messagingSenderId: '578568155957',
    projectId: 'project-flutter-api',
    storageBucket: 'project-flutter-api.appspot.com',
    iosBundleId: 'com.example.testflutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJhDHWBZGumTAXT7n7hNsmf8gScNGeTUE',
    appId: '1:578568155957:ios:80cad8dfd5106a6346127c',
    messagingSenderId: '578568155957',
    projectId: 'project-flutter-api',
    storageBucket: 'project-flutter-api.appspot.com',
    iosBundleId: 'com.example.testflutterApplication1.RunnerTests',
  );
}
